version: '3'

services:
  nginx:
    image: nginx
    restart: always
    volumes: 
      - ../2.8/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80 
      - 443:443
    depends_on:
      - front
      - back

  front:
    image: frontend-example-docker
    restart: always
    expose:
      - 5000
    environment:
      - "API_URL=http://localhost/api"

  back:
    image: backend-example-docker
    restart: always
    expose:
      - 8000
    environment:
      - "FRONT_URL=http://´localhost" 
      - "REDIS=redis"
      - "DB_USERNAME=jan"
      - "DB_PASSWORD=salainen"
      - "DB_NAME=back"
      - "DB_HOST=postgres"
    depends_on: 
      - redis
      - postgres

  redis:
    image: redis:5
    restart: always
    expose:
      - 6379

  postgres:
    image: postgres:latest
    environment:
      - "POSTGRES_DB=back"
      - "POSTGRES_USER=jan"
      - "POSTGRES_PASSWORD=salainen"
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
