FROM ubuntu:16.04
COPY frontend-example-docker frontend-example-docker
RUN apt-get update && \ 
    apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash && \
    apt-get install -y nodejs && \
    npm install && \
    apt-get purge -y --auto-remove curl 

WORKDIR /tmp

EXPOSE 5000
CMD cd frontend-example-docker && npm start

