version: '3'

services:
  nginx:
    image: nginx
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80 
      - 443:443
    depends_on:
      - front
      - back

  front:
    image: frontend-example-docker
    expose:
      - 5000
    environment:
      - "API_URL=http://localhost/api"

  back:
    image: backend-example-docker
    expose:
      - 8000
    environment:
      - "FRONT_URL=http://localhost" 
      - "REDIS=redis"
      - "DB_USERNAME=jan"
      - "DB_PASSWORD=salainen"
      - "DB_NAME=back"
      - "DB_HOST=postgres"
    depends_on: 
      - redis
      - postgres

  redis:
    image: redis:5
    expose:
      - 6379
    entrypoint: redis-server --appendonly yes
    volumes:
      - redis:/data

  postgres:
    image: postgres:latest
    environment:
      - "POSTGRES_DB=back"
      - "POSTGRES_USER=jan"
      - "POSTGRES_PASSWORD=salainen"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes: 
  postgres:
  redis:
